server:
  port: 80

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:7001/eureka

  instance:
    instance-id: order80
    prefer-ip-address: true
spring:
  application:
    name: order80
#设置feign客户端超时时间(OpenFeign默认支持ribbon)(单位：毫秒)
ribbon:
  #指的是建立连接所用的时间，适用于网络状况正常的情况下,两端连接所用的时间
  ReadTimeout: 5000
  #指的是建立连接后从服务器读取到可用资源所用的时间
  ConnectTimeout: 5000


logging:
  level:
  # feign日志以什么级别监控哪个接口
      com.fyking.springcloud.service.PaymentFeignService: debug

#开启
feign:
  hystrix:
    enabled: true

