server:
  port: 8001

spring:
  application:
    name: payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/fyking?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.fyking.springcloud.entities

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:7001/eureka

  instance:
    instance-id: payment8001
    prefer-ip-address: true


